name: Build check

on:
  push:
    paths-ignore:
      - '**.md'
      - 'images/**'
  pull_request:
    types: [assigned, edited, opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go 1.23
        uses: actions/setup-go@v1
        with:
          go-version: 1.23
          timeout: 5m

      # step 2: checkout repository code
      - name: Checkout code into workspace directory
        uses: actions/checkout@v2

      # step 3: install dependencies
      - name: Install all Go dependencies
        run: go get

      # step 4: Run gofmt
      - name: Check that code complies with gofmt requirements
        run: make fmtcheck

      # step 5: source code static analysis
      - name: Run a source code static analysis plus a number of other checkers
        run: make lint

      # step 4: run test
      - name: Run the tests
        run: make test

      # step 5: trivy scan
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: 'fs'
          ignore-unfixed: true
          format: 'sarif'
          output: 'trivy-results.sarif'
          severity: 'CRITICAL,HIGH'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'
